# Generated by Django 4.2.7 on 2025-09-07 10:51

from django.db import migrations
from django.contrib.auth.models import User


def create_staff_accounts(apps, schema_editor):
    """Create default staff accounts for the application."""
    UserProfile = apps.get_model('issues', 'UserProfile')

    # Create staff1 account
    if not User.objects.filter(username='staff1').exists():
        user1 = User.objects.create_user(
            username='staff1',
            password='password123',
            email='staff1@example.com',
            first_name='Staff',
            last_name='One',
            is_staff=True,
            is_active=True
        )
        UserProfile.objects.create(user=user1, role='Staff')

    # Create staff2 account
    if not User.objects.filter(username='staff2').exists():
        user2 = User.objects.create_user(
            username='staff2',
            password='password123',
            email='staff2@example.com',
            first_name='Staff',
            last_name='Two',
            is_staff=True,
            is_active=True
        )
        UserProfile.objects.create(user=user2, role='Staff')


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_accepted_by_issue_bounty_amount'),
    ]

    operations = [
        migrations.RunPython(create_staff_accounts),
    ]
